### ISSUE TITLE
Memory Access Violation

### ISSUE THREAD

**Issue by runxmedia** [WalkerKnapp/devolay#8] opened 2019-12-27 15:54 UTC
Thank you so much for working through everything with me! I successfully have NDI working on my cross platform app thanks to your wrapper.
I'm running into an issue however with memory management. I've found that if I call the close function on the frames, I eventually will get a memory Access Violation on Windows or a seg fault on Mac. When running at 30 fps it usually happens in under a minute.

If I remove the calls to close the frames I no longer get memory Access Violations, but my memory usage runs away. Java garbage collection doesn't free up the memory (at least not fast enough) and I end up filling up system memory within minute or two.

**Comment by runxmedia** [comment] 2019-12-27 15:59
For reference, this is the receiver code I'm using, based on your example code:


        public void receive() {

            Devolay.loadLibraries();
            DevolayReceiver receiver;

            // Connect to the source
            receiver = new DevolayReceiver(source, DevolayReceiver.ColorFormat.RGBX_RGBA,1000,true,"STREAMNAME");
            receiver.connect(source);

            // Create initial frames to be used for capturing
            DevolayVideoFrame videoFrame = new DevolayVideoFrame();
            DevolayAudioFrame audioFrame = new DevolayAudioFrame();
            DevolayMetadataFrame metadataFrame = new DevolayMetadataFrame();

            //Get resolution information from an initial frame
            while (receiver.receiveCapture(videoFrame, audioFrame, metadataFrame, 5000) != DevolayFrameType.VIDEO){
                //do nothing until we get the first video frame
            }
            int x_resolution = videoFrame.getXResolution();
            int y_resolution = videoFrame.getYResolution();
            int total_pixels = x_resolution*y_resolution;
            BufferedImage img = new BufferedImage(x_resolution, y_resolution, BufferedImage.TYPE_INT_ARGB);
            int[] int_array = ((DataBufferInt)img.getRaster().getDataBuffer()).getData();
            final int ALPHA = 0b11111111000000000000000000000000;

            //Loop
            while (receiving) {
                DevolayFrameType type = receiver.receiveCapture(videoFrame, audioFrame, metadataFrame, 1000);
                switch (type) {
                    case VIDEO:
                        ByteBuffer data_array = videoFrame.getData();
                        for(int i = 0; i < total_pixels; i++){

                            int calculated = i*4;
                            int_array[i]= ALPHA+((data_array.get(calculated)) << 16)+((data_array.get((calculated)+1)) << 8)+(data_array.get((calculated)+2));
                        }
                        monitor.newFrame(img);
                        videoFrame = new DevolayVideoFrame();
                        break;
                    case AUDIO:
                        audioFrame = new DevolayAudioFrame();
                        break;
                    case METADATA:
                        metadataFrame = new DevolayMetadataFrame();
                        break;
                    default:
                        break;
                }
                if (receiver.getConnectionCount() < 1) {
                    System.out.println("Lost connection.");
                    monitor.setVideoState(VideoMonitor.VideoState.NO_SIGNAL);
                }
            }

            monitor.setVideoState(VideoMonitor.VideoState.NO_INPUT);

            try (DevolayPerformanceData performanceData = new DevolayPerformanceData()) {
                receiver.queryPerformance(performanceData);
                System.out.println("Dropped Video: " + performanceData.getDroppedVideoFrames() + "/" + performanceData.getTotalVideoFrames());
                System.out.println("Dropped Audio: " + performanceData.getDroppedAudioFrames() + "/" + performanceData.getTotalAudioFrames());
            }

        }

**Comment by bdunkleysmith** [comment] 2019-12-28 04:04
Just for reference, I'm seeing no such memory problems in using your wrapper (as the basis for a B4J Windows application), even after receiving/displaying an NDI video stream of 1280 x 720 50fps for over 1 1/2 hours. That application closes each received frame before processing the next.

**Comment by runxmedia** [comment] 2020-01-02 07:28
@bdunkleysmith do you mind if i see a snippet of your receiver loop? Maybe I'm doing something wrong here

**Comment by bdunkleysmith** [comment] 2020-01-02 09:20
I'm happy to share my code @mporetvivint , however I do not code (directly) in Java, but use [Anywhere Software's B4J](https://www.b4x.com/b4j.html). The IDE uses a Basic-like code and generates an executable Jar.

Below is the code snippet and just like I sometimes need to convert Java to B4J syntax, I'm sure you could do the reverse. One of the issues I faced was converting the received ByteBuffer data to a format which could be handled by the image viewer and @moster67 assisted there by including a getByteArrayFromByteBuffer method in his B4J library wrapper of @WalkerKnapp original work. Here are couple of links to discussions I've had on the B4J Forum: [NDI SDK](https://www.b4x.com/android/forum/threads/ndi-sdk.111950/) and [Write image data from buffer to a bitmap](https://www.b4x.com/android/forum/threads/write-image-data-from-buffer-to-a-bitmap.112125/).

`Sub RxNDI
	' // Connect to the selected source
	Log("Connecting to source: " & Finder.CurrentSources(cmbNDISource.SelectedIndex).GetSourceName)
	Dim receiver As DevolayReceiver
	receiver.Initialize2(Finder.CurrentSources(cmbNDISource.SelectedIndex), receiver.COLOR_FORMAT_BGRX_BGRA, receiver.RECEIVE_BANDWIDTH_HIGHEST, True, Null)
	receiver.Connect(Finder.CurrentSources(cmbNDISource.SelectedIndex))
	Finder.Close
	
	' // Create initial frames to be used for capturing
	Dim videoframe As DevolayVideoFrame
	videoframe.Initialize
	Dim audioframe As DevolayAudioFrame
	audioframe.Initialize
	Dim metadataframe As DevolayMetadataFrame
	metadataframe.Initialize
	
	Do While btnNDIVideo.selected = True
		' // Capture with a timeout of 5000 milliseconds
		Dim Rx1 As DevolayFrameTypeEnum
		Rx1 = receiver.receiveCapture(videoframe,audioframe,metadataframe,5000)
		Select Rx1.getValue
			Case Rx1.NONE
				Log("No data received")
			Case Rx1.VIDEO
				Dim videodata As ByteBuffer
				videodata.Initialize(videoframe.GetXResolution * videoframe.GetYResolution * 4)
				videodata = videoframe.GetData	
			
				Dim byteArray(videodata.Capacity) As Byte
				byteArray = Dev.getByteArrayFromByteBuffer(videodata)
				
				Dim frame As B4XBitmap
				frame = ConvertToBitmap (byteArray,videoframe.GetXResolution,videoframe.GetYResolution)
				Display.ivMain.SetImage(frame)
				frame = Null
				Sleep(0)
				
				videoframe.close
				Dim videoframe As DevolayVideoFrame
				videoframe.Initialize			
			Case Rx1.AUDIO
				Log("Audio received.")
				audioframe.close
				Dim audioframe As DevolayAudioFrame
				audioframe.Initialize
			Case Rx1.METADATA
				Log("Metadata received (" & metadataframe.getData & ").")
				metadataframe.close
				Dim metadataframe As DevolayMetadataFrame
				metadataframe.Initialize
			Case Rx1.ERROR
				Log("Error received")
			Case Rx1.STATUS_CHANGE
				Log("Status Change received")
			Case Else
				Log("Other return message")
		End Select
		
		If receiver.getConnectionCount < 1 Then
			Log("Lost connection.")
			Exit
		End If	
	Loop
	
	receiver.queryPerformance(performancedata)
	Log("Dropped video: " & performancedata.getDroppedVideoFrames & "/" & performancedata.getTotalVideoFrames)
	Log("Dropped audio: " & performancedata.getDroppedAudioFrames & "/" & performancedata.getTotalAudioFrames)
	
	'Destroy the references to each. Not necessary, but can free up the memory faster than Java's GC by itself
	videoframe.close
	audioframe.close
	metadataframe.close
End Sub`

**Comment by runxmedia** [comment] 2020-01-02 16:46
Thanks for that snippet! Very helpful! It looks like you are doing just about the same thing as I am, so I'm at a total loss at this point. I've even tried re-using the same videoFrame instead of creating a new one every time, but that also leads to a seg-fault

**Comment by bdunkleysmith** [comment] 2020-01-03 00:04
I am finding NDI is very demanding of resources, including LAN performance and as a result of your comment about memory problems I thought I'd investigate a little.

I've compared the memory usage of my B4J application, the Studio Monitor from NewTek's NDI tools and the VB WPF Receive Example from NewTek's examples.

Here is what Windows Resource Monitor shows:

At application startup:

![image](https://user-images.githubusercontent.com/58616953/71699689-edad4280-2e14-11ea-93aa-2ba43d6990c7.png)


Consuming 720p 50fps NDI stream:

![image](https://user-images.githubusercontent.com/58616953/71699694-fbfb5e80-2e14-11ea-95ff-98e92676f80c.png)

So I can see that the my Java application is consuming many time more memory that the other applications performing the same task. For comparison, if I change the setting of my application from RECEIVE_BANDWIDTH_HIGHEST to RECEIVE_BANDWIDTH_LOWEST, the memory usage drops to around 600,000KB, but then I finish up with 640x360 frame at 25fps.

I'm not sure what can be done, but clearly my application is far less efficient in its memory use than the other applications.

**Comment by runxmedia** [comment] 2020-01-03 16:31
I figured out a solution to the memory access violation.. Before I started my main frame receiving loop, I pulled out the first frame to get size information for the stream. I did that by inserting this just before my main loop:

            //Get resolution information from an initial frame
            while (receiver.receiveCapture(videoFrame, audioFrame, metadataFrame, 5000) != DevolayFrameType.VIDEO){
                //do nothing until we get the first video frame
            }

Yes, I know using a while loop like that is dangerous and incredibly bad practice, but I never got stuck in that loop during my testing phase.

I found that if I removed this initial - pre loop call to receiver.receiveCapture() I no longer got memory access violations/seg faults by calling close() on the frames. I'm not sure if this is a bug in the native code or if it's just me not understanding the internals of how receiveCapture() works. 

The work-around I made was to just calculate all of the size information I need on the first iteration of the main loop as follows:

case VIDEO:
                        if(first){
                            first = false;
                            x_resolution = videoFrame.getXResolution();
                            y_resolution = videoFrame.getYResolution();
                            total_pixels = x_resolution*y_resolution;
                            img = new BufferedImage(x_resolution, y_resolution, BufferedImage.TYPE_INT_ARGB);
                            int_array = ((DataBufferInt)img.getRaster().getDataBuffer()).getData();
                        }
                        ByteBuffer data_array = videoFrame.getData();
                        for(int i = 0; i < total_pixels; i++){

                            int calculated = i*4;
                            int_array[i]= ALPHA+((data_array.get(calculated)) << 16)+((data_array.get((calculated)+1)) << 8)+(data_array.get((calculated)+2));
                        }
                        monitor.newFrame(img);
                        videoFrame.close();
                        videoFrame = new DevolayVideoFrame();
                        break;
@bdunkleysmith Yes I've observed the same. My application uses about 1.5GB of memory for 3 simultaneous 1080p streams. (It uses about 500mb of memory without the streams. It's a pretty heavy fella) But I'm not too concerned with that myself. All of the broadcast machines have WAY more than enough memory to handle that, and only run one task at a time

**Comment by WalkerKnapp** [comment] 2020-01-03 18:11
I apologize again for the wait, but I finally got back from vacation. Thank you both for documenting what causes this issue so well. I believe this is a bug in the native NDI SDK's NDIlib_recv_free_video_v2 function, which gets called with DevolayVideoFrame#close. I also took some time to restructure how video receiving can happen, so now it should be a lot more natural to work with.

I'm still working on getting a snapshot release, but the latest commit should have these changes:
- There is now a Devolay*Frame#freeBuffer method to free a buffer allocated by #receiveCapture without needing to recreate the object
- #receiveCapture now calls #freeBuffer for all frames passed to it, so frames no longer need to be manually cleared or reallocated in most circumstances

The receive example code went from:
``` while(System.currentTimeMillis() - startTime < 1000 * 60) {
            // Capture with a timeout of 5000 milliseconds
            switch (receiver.receiveCapture(videoFrame, audioFrame, metadataFrame, 5000)) {
                case NONE:
                    System.out.println("No data received.");
                    break;
                case VIDEO:
                    System.out.println("Video data received (" + videoFrame.getXResolution() + "x" + videoFrame.getYResolution() + ", " +
                            videoFrame.getFrameRateN() + "/" + videoFrame.getFrameRateD() + ").");

                    videoFrame.close();
                    videoFrame = new DevolayVideoFrame();
                    break;
                case AUDIO:
                    System.out.println("Audio data received (" + audioFrame.getSamples() + ", " + audioFrame.getChannelStride() + ").");
                    audioFrame.close();
                    audioFrame = new DevolayAudioFrame();
                    break;
                case METADATA:
                    System.out.println("Metadata received (" + metadataFrame.getData() + ").");
                    metadataFrame.close();
                    metadataFrame = new DevolayMetadataFrame();
                    break;
            }
```
to
```
        while(System.currentTimeMillis() - startTime < 1000 * 60) {
            // Capture with a timeout of 5000 milliseconds
            // This method now explicitly clears data from videoFrame, audioFrame, and metadataFrame that was previously allocated
            switch (receiver.receiveCapture(videoFrame, audioFrame, metadataFrame, 5000)) {
                case NONE:
                    System.out.println("No data received.");
                    break;
                case VIDEO:
                    System.out.println("Video data received (" + videoFrame.getXResolution() + "x" + videoFrame.getYResolution() + ", " +
                            videoFrame.getFrameRateN() + "/" + videoFrame.getFrameRateD() + ").");
                    break;
                case AUDIO:
                    System.out.println("Audio data received (" + audioFrame.getSamples() + ", " + audioFrame.getChannelStride() + ").");
                    break;
                case METADATA:
                    System.out.println("Metadata received (" + metadataFrame.getData() + ").");
                    break;
            }
```

**Comment by WalkerKnapp** [comment] 2020-01-03 20:16
I just published the `1.2.0-snapshot` version on bintray with these changes. From some preliminary testing, it looks like this resolved the issue, but I'd appreciate it if you could test it on your system with your program.

I'll look into memory usage later, but I'd imagine most of the issues and leaks can be solved with changes to individual implementations.

**Comment by runxmedia** [comment] 2020-01-03 20:20
That looks great! Thanks for all your help

**Comment by runxmedia** [comment] 2020-01-03 20:28
After a quick test on my system, removing the frame.close() and new frame calls, it seems to be working just fine. I'll keep you posted with any other findings

**Comment by WalkerKnapp** [comment] 2020-01-03 20:52
Alright, thank you! I'll close this issue for now and open another for the memory issues. Feel free to reopen if you have any other issues.

**Closed as completed by WalkerKnapp** 2020-01-03 20:52 UTC

**Comment by chinhodado** [comment] 2022-02-22 15:18
@WalkerKnapp I know this has been a while but can you explain a bit the fix you made for this please? I'm running into a similar issue with memory corruption with the NDI library, although I'm not using devolay. I'm reading commit 97941921943b81e78953250863363d1043af19d0 which I think is what the fix is, and I don't immediately understand how the fix works.

**Comment by WalkerKnapp** [comment] 2022-02-22 16:53
@chinhodado Thanks for asking! ~~This was a few years ago now, but I believe the fix boiled down adding infrastructure to avoid repeatedly calling `NDIlib_recv_free_video_v2` (and its equivalent for metadata/audio) altogether, only calling it after the receive loop completes to clear up resources. I wish it was a more satisfying fix, but I believe I never worked out exactly why calling it could cause segfaults.~~

Edit: Actually, I believe I was misinterpreting this code, that isn't what was changed. Give me a bit longer to see if I can figure out what was happening

I didn't have this luxury with JNI, but if you are working in an environment where you can attach a debugger and get the program's state upon crashes, it would be interesting to see if we could identify a pattern in frame structs that causes it.

**Comment by WalkerKnapp** [comment] 2022-02-22 17:15
Ah, I think this was probably it. The change was infrastructure to avoid repeatedly creating new frames with `new NDIlib_video_frame_v2_t`. 

I didn't realize it at the time, but I think that the memory corruption we were seeing was caused by uninitialized garbage data in the `NDIlib_video_frame_v2_t` struct being read (for some reason) by `NDIlib_recv_capture_v2`. That would explain why it would come up more often as we create many frames and free/reuse a lot of memory.

Try explicitly setting `p_data` and `p_metadata` (and audio/metadata equivalents) to nullptr before running `recv_capture`. If you did take a look at this with a debugger, it would be interesting to see if memory corruption immediately follows a `NDIlib_recv_capture_v2` with errant data in those 2 fields.

**Comment by chinhodado** [comment] 2022-02-22 21:58
Thank you so much for the quick response! Turned out the issue was much simpler. I was digging around devolay code looking for clue and found this comment:

https://github.com/WalkerKnapp/devolay/blob/release/devolay-java/src/main/java/me/walkerknapp/devolay/DevolayVideoFrame.java#L10

```
    // set when a buffer is allocated by a receiver that later needs to be freed w/ that receiver.
    AtomicReference<DevolayFrameCleaner> allocatedBufferSource = new AtomicReference<>();
```

and then it dawned on me, because of some threading issues, I was not passing in the correct receiver to the memory free functions. Fixed that and it's all working well now!

On another note, do you know how NDI discovery server works for NDI client by any chance? The SDK docs don't mention any API for it (e.g. NDI_find doesn't seem to take in any param for discovery sever), and it seems it just works if you use NDI Access Manager on the client machine and put in the discovery server address?

**Comment by WalkerKnapp** [comment] 2022-02-23 01:04
> NDI discovery server works for NDI client by any chance?

The NDI Advanced SDK documentation mentions it a few times in the configuration section. It doesn't seem extremely precise, and I personally don't have much experience using the Advanced SDK or its features, so I wont be much help seeing if that will work for you. Hope you can find what you need there, though!
